SampleFileName: clean_df.csv
NumberOfColumns: 28
Columns:
  ID: int
  Customer_ID: int
  Month: int
  Name: category
  Age: float
  SSN: float
  Occupation: category
  Annual_Income: float
  Monthly_Inhand_Salary: float
  Num_Bank_Accounts: float
  Num_Credit_Card: float
  Interest_Rate: float
  Num_of_Loan: float
  Type_of_Loan: category
  Delay_from_due_date: float
  Num_of_Delayed_Payment: float
  Changed_Credit_Limit: float
  Num_Credit_Inquiries: float
  Credit_Mix: category
  Outstanding_Debt: float
  Credit_Utilization_Ratio: float64
  Credit_History_Age: float64
  Payment_of_Min_Amount: category
  Total_EMI_per_month: float64
  Amount_invested_monthly: float64
  Payment_Behaviour: category
  Monthly_Balance: float64
  Credit_Score: category


target_column:
  Credit_Score


numerical_columns: 
  Age
  Annual_Income
  Monthly_Inhand_Salary
  Interest_Rate
  Delay_from_due_date
  Num_of_Delayed_Payment
  Changed_Credit_Limit
  Outstanding_Debt
  Credit_Utilization_Ratio
  Credit_History_Age
  Total_EMI_per_month
  Amount_invested_monthly
  Monthly_Balance


Transformation_columns:
  Delay_from_due_date
  Interest_Rate
  Num_of_Delayed_Payment
  Num_Credit_Card
  Annual_Income
  Monthly_Inhand_Salary
  Outstanding_Debt
  Credit_Utilization_Ratio
  Credit_History_Age
  Total_EMI_per_month
  Amount_invested_monthly
  Monthly_Balance
  Num_Bank_Accounts
  Num_Credit_Inquiries
  Changed_Credit_Limit
  Num_of_Loan



Oridnal_columns: 
  Occupation
  Credit_Mix

Onehot_columns: 
  
  Payment_Behaviour
  Credit_Score

drop_columns: 
  _id
  SSN
  Name
  ID
  Customer_ID



  